### ISSUE TITLE
Update allocation with --expiry flag is still not working

### ISSUE THREAD

**Issue by shaktals** [0chain/zboxcli#94]
This continues discussion of #34, which is a blocker for the `block-explorer` issue [205](https://github.com/0chain/block-explorer/issues/205).
ping @andrenerd @stewartie4 @Sriep

**Comment by stewartie4** [comment]
It looks like when you update an allocation with a given size it works every time.
If you try to update the expiry date of the allocation (expire it or extend it) this never works and the subsequent confirmation will fail.
Therefore I believe this to be a bug in the smart contract

**Comment by Sriep** [comment]
Please check that every blobber can support the extension proposed.

**Comment by stewartie4** [comment]
I have tried reducing by 1 hour and extending by 1 hour directly to the API of multiple blobbers, it never works for me nor the cli

**Comment by shaktals** [comment]
Same here, just tried twice with different time periods, the error persists. [(cli error image)](https://user-images.githubusercontent.com/24679343/130500577-c7cfbcd9-5a0a-47d3-9926-590587d39bf3.png)

**Comment by shaktals** [comment]
Maybe some API integration tests here would be nice? :thinking:

**Comment by Sriep** [comment]
900 hours might be too much. Try 48h.

**Comment by shaktals** [comment]
Ah, the docs suggest 900h as an example.
The cli worked when using 48h.
But the `block-explorer` extend expiry unit is **months**!
I just tried with 1 month and it worked.
Maybe that is the problem?
If so, then we'll have to change the unit, implement restrictions.
What is the time limit then?

**Comment by guruhubb** [comment]
The sc.yaml has the time limit - we should do an API to check all min/max limits of the network. @Sriep is working on that with cli.

**Comment by shaktals** [comment]
Got it. One thing I noticed now is that extending 1 month via `explorer` UI worked on `dev` network, but not on `beta`.
Do you guys know that is the time limit there?
We'll change the extend expiry input to `hours`, and set that limit.

**Comment by stewartie4** [comment]
@shaktals we have API integration tests 
https://0chain.github.io/0chain/beta/2021-08-23_17.05.29/index.html#pills-requests
this test scenario is disabled currently as it always fails

**Comment by shaktals** [comment]
@stewartie4 here is a sample [request data](https://github.com/0chain/zboxcli/files/7035405/Update.alloc.txt), that worked on `beta`.
I'm having the following issue in the `dev` network, so I can't get it to work there:
`internal_error: selecting blobbers: Not enough blobbers to honor the allocation`

**Comment by shaktals** [comment]
> @shaktals we have API integration tests
> https://0chain.github.io/0chain/beta/2021-08-23_17.05.29/index.html#pills-requests
> this test scenario is disabled currently as it always fails

@moldis Saswata was asking me about this issue, do you know if it has been solved?

**Comment by shaktals** [comment]
@moldis @stewartie4 do we have news here?

**Comment by stewartie4** [comment]
This seems to have been resolved on staging images:
![image](https://user-images.githubusercontent.com/18306778/136177238-a312fa03-dd1b-434e-a5ae-18cc963014ad.png)
I'm not sure who resolved this, or what the issue was, does anyone here know?
Cancel allocation remains broken

**Comment by shaktals** [comment]
We'll test this out on the explorer and cli, then close this if it's solved.

**Comment by webPlayer7** [comment]
Update allocation using zboxcli still fails with --expiry flag. Same on the block-explorer.
I can't find the correct reason why it fails. It works fine without --expiry.

**Comment by shaktals** [comment]
@JordanMicle2019 please provide the cli command you used, and the cli response log for context.

**Comment by webPlayer7** [comment]
`./zbox updateallocation --allocation df278b739c1ade8495ce76ecd351baf29ce494a72679ccdcb04ffdc884d8c8cf --expiry 48h --size 4096`
Here is command and result
![Screenshot_3](https://user-images.githubusercontent.com/53501353/137382623-0b99b985-de81-4ff1-aa02-c3193fedbe2f.jpg)

**Comment by stewartie4** [comment]
@JordanMicle2019 try running against dev.0chain.net - beta.0chain.net is on master images which i don't believe have the fix

**Comment by webPlayer7** [comment]
@stewartie4  On dev.0chain.net, create allocation fails and also update allocation. On beta, create allocation and update allocation without `--expiry` flag worked 
![Screenshot_3](https://user-images.githubusercontent.com/53501353/137428155-e74ec89a-16f8-4998-a2d9-e7cf82f0612f.jpg)

**Comment by stewartie4** [comment]
Ok this looks like an issue with your CLI build as allocation create on dev is working everywhere else 
Maybe try rebuilding it?

**Comment by webPlayer7** [comment]
You mean `make install` again?

**Comment by webPlayer7** [comment]
I did `make install` and then retried to create allocation on `dev `network. But got same error

**Comment by shaktals** [comment]
What `zboxcli` branch are you using @JordanMicle2019? Did you pull the latest changes to that branch?

**Comment by webPlayer7** [comment]
For zboxcli, I am using staging branch. And yeah I pulled latest one

**Comment by shaktals** [comment]
@stewartie4 I can confirm Jordan's error, I'm getting the same from the `test` network on a freshly pulled and compiled `zboxcli` (staging):

![Selection_164](https://user-images.githubusercontent.com/24679343/137773322-cc0981f4-ca06-4cdd-b98a-f9874bc496d3.png)

**Comment by shaktals** [comment]
> @stewartie4 I can confirm Jordan's error, I'm getting the same from the `test` network on a freshly pulled and compiled `zboxcli` (staging):

Even without the `expire` flag is not working.

**Comment by stewartie4** [comment]
@shaktals The issue here is the network
nothing is passing against 
test.0chain.net 
https://github.com/0chain/system_test/runs/3929454464?check_suite_focus=true 

all of this works fine against 
dev.0chain.net
https://github.com/0chain/system_test/runs/3929457526?check_suite_focus=true

**Comment by shaktals** [comment]
I just confirmed it works against `dev` network, closing this.
